### ISSUE TITLE
Fix Spotlight

### ISSUE THREAD

**Issue by shaurya5** [arc-bphc/arc-site#13]
Refreshing doesn't change the first person card

**Comment by thenicekat** [comment]
Probably SSR thing?

**Comment by thenicekat** [comment]
Scam, math.random always generating 0 as one number

**Comment by thenicekat** [comment]
@shaurya5 so the issue is fixed, but it does give warnings because, CSR is re-rendering the random numbers while SSR isn't

**Comment by shaurya5** [comment]
yeah works for now. I'll reopen if there's an issue
